apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: bible-data-endpoints
  name: bible-data-endpoints
  namespace: default
spec:
  replicas: 1 #CHANGE
  minReadySeconds: 45
  selector:
    matchLabels:
      app: bible-data-endpoints
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: bible-data-endpoints
    spec:
      containers:
        - image: bibleit/bible-data-endpoints:0.0.3-SNAPSHOT   #CHANGE
#          imagePullPolicy: IfNotPresent
          imagePullPolicy: Always
          name: bible-data-endpoints
          env:
            - name: JSON_PARSER_URI
              value: http://bible-json-parser
      #          - name: SPRING_PROFILES_ACTIVE
      #            value: kubernetes
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels: #PODS
    app: bible-data-endpoints
  name: bible-data-endpoints
  namespace: default
spec:
  ports:
    - # nodePort: 30701 #CHANGE
      port: 8100 #CHANGE
      protocol: TCP
      targetPort: 8100 #CHANGE
  selector:
    app: bible-data-endpoints
  sessionAffinity: None #CHANGE
  type: NodePort