apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: bible-json-parser
  name: bible-json-parser
  namespace: default
spec:
  replicas: 1 #CHANGE
  minReadySeconds: 45
  selector:
    matchLabels:
      app: bible-json-parser
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: bible-json-parser
    spec:
      containers:
        - image: bibleit/bible-json-parser:0.0.2-SNAPSHOT #CHANGE
          imagePullPolicy: IfNotPresent
          name: bible-json-parser
          ports:
            - name: liveness-port
              containerPort: 8000
          resources: #CHANGE
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1024Mi #256Mi
          readinessProbe:
            httpGet:
              path: /
              port: liveness-port
            failureThreshold: 5
            periodSeconds: 10
            initialDelaySeconds: 60
          livenessProbe:
            httpGet:
              path: /
              port: liveness-port
            failureThreshold: 5
            periodSeconds: 10
            initialDelaySeconds: 60
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels: #PODS
    app: bible-json-parser
  name: bible-json-parser
  namespace: default
spec:
  ports:
    - # nodePort: 30702 #CHANGE
      port: 8000 #CHANGE
      protocol: TCP
      targetPort: 8000 #CHANGE
  selector:
    app: bible-json-parser
  sessionAffinity: None #CHANGE
  type: NodePort